meta_product_name: "Monetizeur"
meta_title: "Monetizeur - Never make an unwanted payment again"
meta_description: "Monetizeur is the all in one subscription manager that gets you organized and helps track your spending."
meta_image: "monetizeur-logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
